import type { Exercise } from "@/types";

export const EXERCISES: Exercise[] = [
  // Chest
  { id: "bench-press", name: "Bench Press", category: "Chest", musclesWorked: ["Chest", "Triceps", "Shoulders"], description: "The fundamental compound pressing movement. Lie flat, lower the bar to mid-chest, press up." },
  { id: "incline-bench", name: "Incline Bench Press", category: "Chest", musclesWorked: ["Upper Chest", "Triceps", "Shoulders"], description: "Targets the upper chest. Set bench to 30–45° incline." },
  { id: "decline-bench", name: "Decline Bench Press", category: "Chest", musclesWorked: ["Lower Chest", "Triceps"], description: "Emphasizes lower chest fibers with a slight decline angle." },
  { id: "db-bench-press", name: "Dumbbell Bench Press", category: "Chest", musclesWorked: ["Chest", "Triceps", "Shoulders"], description: "Greater range of motion than the barbell. Press dumbbells from chest level." },
  { id: "incline-db-press", name: "Incline Dumbbell Press", category: "Chest", musclesWorked: ["Upper Chest", "Triceps", "Shoulders"], description: "Upper-chest builder with a deep stretch. Bench at 30–45°." },
  { id: "decline-db-press", name: "Decline Dumbbell Press", category: "Chest", musclesWorked: ["Lower Chest", "Triceps"], description: "Lower-chest emphasis with independent arm control." },
  { id: "machine-chest-press", name: "Machine Chest Press", category: "Chest", musclesWorked: ["Chest", "Triceps", "Shoulders"], description: "Fixed path pressing. Great for controlled, high-rep chest work." },
  { id: "incline-machine-press", name: "Incline Machine Chest Press", category: "Chest", musclesWorked: ["Upper Chest", "Triceps", "Shoulders"], description: "Upper-chest press on a guided machine. Stable and joint-friendly." },
  { id: "smith-bench-press", name: "Smith Machine Bench Press", category: "Chest", musclesWorked: ["Chest", "Triceps", "Shoulders"], description: "Bar on a fixed vertical path. Easy to unrack and overload safely." },
  { id: "smith-incline-press", name: "Smith Machine Incline Press", category: "Chest", musclesWorked: ["Upper Chest", "Triceps"], description: "Guided incline press for upper-chest overload." },
  { id: "pec-deck", name: "Pec Deck Machine", category: "Chest", musclesWorked: ["Chest"], description: "Seated machine fly. Constant tension with a strong peak contraction." },
  { id: "dumbbell-fly", name: "Dumbbell Fly", category: "Chest", musclesWorked: ["Chest"], description: "Isolation movement. Wide arc motion to stretch and contract the pecs." },
  { id: "incline-db-fly", name: "Incline Dumbbell Fly", category: "Chest", musclesWorked: ["Upper Chest"], description: "Fly variation targeting the upper chest through a big stretch." },
  { id: "cable-crossover", name: "Cable Crossover", category: "Chest", musclesWorked: ["Chest"], description: "Constant tension through the full range of motion." },
  { id: "low-cable-fly", name: "Low-to-High Cable Fly", category: "Chest", musclesWorked: ["Upper Chest"], description: "Pulleys set low, sweep upward. Emphasizes the upper chest." },
  { id: "high-cable-fly", name: "High-to-Low Cable Fly", category: "Chest", musclesWorked: ["Lower Chest"], description: "Pulleys set high, sweep down. Emphasizes the lower chest." },
  { id: "incline-cable-fly", name: "Incline Cable Fly", category: "Chest", musclesWorked: ["Upper Chest"], description: "Cable fly on an incline bench for constant upper-chest tension." },
  { id: "push-up", name: "Push-Up", category: "Chest", musclesWorked: ["Chest", "Triceps", "Core"], description: "Bodyweight pressing movement. Hands shoulder-width, full range of motion." },
  { id: "dips-chest", name: "Chest Dips", category: "Chest", musclesWorked: ["Chest", "Triceps"], description: "Lean forward to emphasize chest over triceps." },
  { id: "weighted-dips-chest", name: "Weighted Chest Dips", category: "Chest", musclesWorked: ["Chest", "Triceps"], description: "Add load via belt or dumbbell. Lean forward for chest emphasis." },
  { id: "landmine-press", name: "Landmine Press", category: "Chest", musclesWorked: ["Upper Chest", "Shoulders", "Triceps"], description: "Press a barbell end at an angle. Shoulder-friendly upper-chest work." },
  { id: "svend-press", name: "Svend Press", category: "Chest", musclesWorked: ["Chest"], description: "Squeeze plates together and press out. Pure inner-chest contraction." },

  // Back
  { id: "deadlift", name: "Deadlift", category: "Back", musclesWorked: ["Back", "Glutes", "Hamstrings", "Core"], description: "King of all lifts. Hinge at hips, neutral spine, drive through the floor." },
  { id: "rack-pull", name: "Rack Pull", category: "Back", musclesWorked: ["Back", "Traps", "Glutes"], description: "Partial deadlift from pins. Overloads the upper back and lockout." },
  { id: "pull-up", name: "Pull-Up", category: "Back", musclesWorked: ["Lats", "Biceps"], description: "Overhand grip, full hang to chin over bar. The gold standard for back width." },
  { id: "wide-pull-up", name: "Wide-Grip Pull-Up", category: "Back", musclesWorked: ["Lats", "Biceps"], description: "Wider grip biases lat width and the upper back." },
  { id: "chin-up", name: "Chin-Up", category: "Back", musclesWorked: ["Lats", "Biceps"], description: "Underhand grip. More bicep involvement than pull-up." },
  { id: "inverted-row", name: "Inverted Row", category: "Back", musclesWorked: ["Back", "Biceps"], description: "Body-weight horizontal pull under a fixed bar. Scalable for any level." },
  { id: "barbell-row", name: "Barbell Row", category: "Back", musclesWorked: ["Back", "Biceps", "Core"], description: "Hinged position, pull bar to lower chest. Squeeze shoulder blades." },
  { id: "pendlay-row", name: "Pendlay Row", category: "Back", musclesWorked: ["Back", "Biceps", "Core"], description: "Explosive row from a dead stop on the floor each rep." },
  { id: "dumbbell-row", name: "Dumbbell Row", category: "Back", musclesWorked: ["Back", "Biceps"], description: "One arm braced on a bench. Big stretch and full contraction." },
  { id: "chest-supported-row", name: "Chest-Supported Row", category: "Back", musclesWorked: ["Back", "Biceps"], description: "Torso braced on a pad. Removes lower-back and momentum." },
  { id: "machine-row", name: "Machine Row", category: "Back", musclesWorked: ["Back", "Biceps"], description: "Seated plate- or pin-loaded row. Controlled mid-back thickness." },
  { id: "meadows-row", name: "Meadows Row", category: "Back", musclesWorked: ["Back", "Biceps"], description: "Single-arm landmine row. Strong stretch on the lats." },
  { id: "cable-row", name: "Seated Cable Row", category: "Back", musclesWorked: ["Back", "Biceps"], description: "Controlled pull with constant tension. Drive elbows back." },
  { id: "t-bar-row", name: "T-Bar Row", category: "Back", musclesWorked: ["Back", "Biceps"], description: "Neutral grip row for mid-back thickness." },
  { id: "lat-pulldown", name: "Lat Pulldown", category: "Back", musclesWorked: ["Lats", "Biceps"], description: "Wide grip pulldown to upper chest. Depresses scapula." },
  { id: "wide-grip-pulldown", name: "Wide-Grip Lat Pulldown", category: "Back", musclesWorked: ["Lats", "Biceps"], description: "Wider grip for maximum lat width recruitment." },
  { id: "neutral-grip-pulldown", name: "Neutral-Grip Pulldown", category: "Back", musclesWorked: ["Lats", "Biceps"], description: "Palms-facing grip. Comfortable and lat-dominant." },
  { id: "single-arm-pulldown", name: "Single-Arm Lat Pulldown", category: "Back", musclesWorked: ["Lats", "Biceps"], description: "Unilateral pulldown for a longer range and even development." },
  { id: "straight-arm-pulldown", name: "Straight-Arm Pulldown", category: "Back", musclesWorked: ["Lats"], description: "Arms straight, drive the bar down. Isolates the lats." },
  { id: "cable-pullover", name: "Cable Pullover", category: "Back", musclesWorked: ["Lats"], description: "Kneeling or standing lat isolation with constant tension." },
  { id: "face-pull", name: "Face Pull", category: "Back", musclesWorked: ["Shoulders", "Back"], description: "Cable at face height, pull to forehead. Excellent for rear delts." },
  { id: "barbell-shrug", name: "Barbell Shrug", category: "Back", musclesWorked: ["Traps"], description: "Elevate the shoulders straight up. Direct upper-trap builder." },
  { id: "dumbbell-shrug", name: "Dumbbell Shrug", category: "Back", musclesWorked: ["Traps"], description: "Shrug with dumbbells for a longer range than the barbell." },
  { id: "back-extension", name: "Back Extension", category: "Back", musclesWorked: ["Lower Back", "Glutes", "Hamstrings"], description: "Hyperextension bench. Strengthens the spinal erectors and hips." },

  // Shoulders
  { id: "ohp", name: "Overhead Press", category: "Shoulders", musclesWorked: ["Shoulders", "Triceps", "Core"], description: "Press barbell from rack position overhead. Full body stability required." },
  { id: "dumbbell-ohp", name: "Dumbbell Shoulder Press", category: "Shoulders", musclesWorked: ["Shoulders", "Triceps"], description: "Seated or standing. Greater range of motion than barbell." },
  { id: "seated-db-press", name: "Seated Dumbbell Press", category: "Shoulders", musclesWorked: ["Shoulders", "Triceps"], description: "Back supported to isolate the delts. Press dumbbells overhead." },
  { id: "machine-shoulder-press", name: "Machine Shoulder Press", category: "Shoulders", musclesWorked: ["Shoulders", "Triceps"], description: "Guided overhead press. Stable path for controlled delt work." },
  { id: "smith-shoulder-press", name: "Smith Machine Shoulder Press", category: "Shoulders", musclesWorked: ["Shoulders", "Triceps"], description: "Overhead press on a fixed bar path. Easy to overload safely." },
  { id: "arnold-press", name: "Arnold Press", category: "Shoulders", musclesWorked: ["Shoulders", "Triceps"], description: "Rotating press named after Arnold. Full shoulder recruitment." },
  { id: "lateral-raise", name: "Lateral Raise", category: "Shoulders", musclesWorked: ["Shoulders"], description: "Raise arms to 90°, pinky slightly higher. Isolates medial delt." },
  { id: "cable-lateral-raise", name: "Cable Lateral Raise", category: "Shoulders", musclesWorked: ["Shoulders"], description: "Constant tension on the side delt through the whole range." },
  { id: "machine-lateral-raise", name: "Machine Lateral Raise", category: "Shoulders", musclesWorked: ["Shoulders"], description: "Seated machine that isolates the medial delts with a fixed path." },
  { id: "front-raise", name: "Front Raise", category: "Shoulders", musclesWorked: ["Shoulders"], description: "Raise arms forward to shoulder height. Anterior delt focus." },
  { id: "cable-front-raise", name: "Cable Front Raise", category: "Shoulders", musclesWorked: ["Shoulders"], description: "Front delt raise with continuous cable tension." },
  { id: "plate-front-raise", name: "Plate Front Raise", category: "Shoulders", musclesWorked: ["Shoulders"], description: "Hold a plate and raise to eye level. Front-delt isolation." },
  { id: "reverse-fly", name: "Reverse Fly", category: "Shoulders", musclesWorked: ["Shoulders", "Back"], description: "Bent over or on incline bench. Targets rear deltoids." },
  { id: "rear-delt-machine", name: "Rear Delt Machine", category: "Shoulders", musclesWorked: ["Shoulders", "Back"], description: "Reverse pec-deck. Isolates the rear delts with a fixed path." },
  { id: "cable-rear-delt", name: "Cable Rear Delt Fly", category: "Shoulders", musclesWorked: ["Shoulders", "Back"], description: "Crossed cables pulled apart. Constant rear-delt tension." },
  { id: "upright-row", name: "Upright Row", category: "Shoulders", musclesWorked: ["Shoulders", "Traps"], description: "Narrow grip pull to chin. Traps and medial delts." },
  { id: "landmine-shoulder-press", name: "Landmine Shoulder Press", category: "Shoulders", musclesWorked: ["Shoulders", "Triceps"], description: "Single-arm angled press. Shoulder-friendly pressing pattern." },

  // Biceps
  { id: "barbell-curl", name: "Barbell Curl", category: "Biceps", musclesWorked: ["Biceps"], description: "Classic mass builder. Keep elbows stationary, full range." },
  { id: "ez-bar-curl", name: "EZ-Bar Curl", category: "Biceps", musclesWorked: ["Biceps"], description: "Angled grip eases wrist strain while loading the biceps heavily." },
  { id: "dumbbell-curl", name: "Dumbbell Curl", category: "Biceps", musclesWorked: ["Biceps"], description: "Alternating or simultaneous. Supinate at the top." },
  { id: "hammer-curl", name: "Hammer Curl", category: "Biceps", musclesWorked: ["Biceps", "Forearms"], description: "Neutral grip. Targets brachialis and brachioradialis." },
  { id: "incline-hammer-curl", name: "Incline Hammer Curl", category: "Biceps", musclesWorked: ["Biceps", "Forearms"], description: "Neutral grip on an incline bench for a deep stretch." },
  { id: "incline-curl", name: "Incline Dumbbell Curl", category: "Biceps", musclesWorked: ["Biceps"], description: "Greater stretch at bottom position. Excellent for long head." },
  { id: "preacher-curl", name: "Preacher Curl", category: "Biceps", musclesWorked: ["Biceps"], description: "Eliminates cheating. Peak contraction at top." },
  { id: "spider-curl", name: "Spider Curl", category: "Biceps", musclesWorked: ["Biceps"], description: "Chest on an incline bench, arms hanging. Constant short-head tension." },
  { id: "cable-curl", name: "Cable Curl", category: "Biceps", musclesWorked: ["Biceps"], description: "Constant tension throughout range of motion." },
  { id: "cable-hammer-curl", name: "Cable Hammer Curl", category: "Biceps", musclesWorked: ["Biceps", "Forearms"], description: "Rope attachment, neutral grip. Brachialis and forearm focus." },
  { id: "high-cable-curl", name: "High Cable Curl", category: "Biceps", musclesWorked: ["Biceps"], description: "Arms out at shoulder height. Strong peak contraction for the biceps." },
  { id: "concentration-curl", name: "Concentration Curl", category: "Biceps", musclesWorked: ["Biceps"], description: "Seated, elbow on inner thigh. Maximum isolation." },
  { id: "zottman-curl", name: "Zottman Curl", category: "Biceps", musclesWorked: ["Biceps", "Forearms"], description: "Curl up supinated, lower pronated. Hits biceps and forearms." },
  { id: "machine-curl", name: "Machine Curl", category: "Biceps", musclesWorked: ["Biceps"], description: "Fixed-path curl with a pad. Consistent tension, no swinging." },

  // Triceps
  { id: "close-grip-bench", name: "Close-Grip Bench Press", category: "Triceps", musclesWorked: ["Triceps", "Chest"], description: "Shoulder-width grip bench. Best compound tricep exercise." },
  { id: "jm-press", name: "JM Press", category: "Triceps", musclesWorked: ["Triceps"], description: "Hybrid of close-grip bench and skull crusher. Heavy triceps loading." },
  { id: "skull-crusher", name: "Skull Crusher", category: "Triceps", musclesWorked: ["Triceps"], description: "EZ bar or dumbbells lowered to forehead. All three heads." },
  { id: "tricep-pushdown", name: "Tricep Pushdown", category: "Triceps", musclesWorked: ["Triceps"], description: "Cable pushdown with rope or bar. Constant tension." },
  { id: "rope-pushdown", name: "Rope Pushdown", category: "Triceps", musclesWorked: ["Triceps"], description: "Spread the rope at the bottom for a hard lateral-head contraction." },
  { id: "single-arm-pushdown", name: "Single-Arm Pushdown", category: "Triceps", musclesWorked: ["Triceps"], description: "Underhand single-arm cable pushdown. Isolates each side." },
  { id: "reverse-grip-pushdown", name: "Reverse-Grip Pushdown", category: "Triceps", musclesWorked: ["Triceps"], description: "Supinated grip pushdown emphasizing the medial head." },
  { id: "overhead-tricep", name: "Overhead Tricep Extension", category: "Triceps", musclesWorked: ["Triceps"], description: "Maximum long head stretch. Seated dumbbell or cable." },
  { id: "cable-overhead-extension", name: "Cable Overhead Extension", category: "Triceps", musclesWorked: ["Triceps"], description: "Rope overhead from a low pulley. Constant long-head stretch." },
  { id: "db-overhead-extension", name: "Dumbbell Overhead Extension", category: "Triceps", musclesWorked: ["Triceps"], description: "Two-handed dumbbell behind the head. Deep long-head stretch." },
  { id: "machine-tricep-extension", name: "Machine Triceps Extension", category: "Triceps", musclesWorked: ["Triceps"], description: "Seated dip or extension machine. Controlled, high-rep friendly." },
  { id: "dips-tricep", name: "Tricep Dips", category: "Triceps", musclesWorked: ["Triceps", "Chest"], description: "Upright torso to emphasize triceps." },
  { id: "bench-dips", name: "Bench Dips", category: "Triceps", musclesWorked: ["Triceps"], description: "Hands on a bench behind you. Scalable bodyweight triceps work." },
  { id: "diamond-push-up", name: "Diamond Push-Up", category: "Triceps", musclesWorked: ["Triceps", "Chest"], description: "Hands together under the chest. Bodyweight triceps emphasis." },
  { id: "kickback", name: "Tricep Kickback", category: "Triceps", musclesWorked: ["Triceps"], description: "Hinge forward, extend arm back. Lateral head isolation." },

  // Forearms
  { id: "wrist-curl", name: "Barbell Wrist Curl", category: "Forearms", musclesWorked: ["Forearms"], description: "Barbell in both hands, forearms on a bench, palms up. Curl the wrists to build the flexors." },
  { id: "dumbbell-wrist-curl", name: "Dumbbell Wrist Curl", category: "Forearms", musclesWorked: ["Forearms"], description: "One dumbbell per hand over a bench, palms up. Lets each wrist work through its full range." },
  { id: "machine-wrist-curl", name: "Machine Wrist Curl", category: "Forearms", musclesWorked: ["Forearms"], description: "Seated at a wrist-curl or preacher-style machine, palms up. Constant tension on the flexors." },
  { id: "reverse-wrist-curl", name: "Barbell Reverse Wrist Curl", category: "Forearms", musclesWorked: ["Forearms"], description: "Barbell with a palms-down grip on a bench. Wrist extension for the forearm extensors." },
  { id: "dumbbell-reverse-wrist-curl", name: "Dumbbell Reverse Wrist Curl", category: "Forearms", musclesWorked: ["Forearms"], description: "Dumbbells palms-down over a bench. Independent extension for each forearm." },
  { id: "machine-reverse-wrist-curl", name: "Machine Reverse Wrist Curl", category: "Forearms", musclesWorked: ["Forearms"], description: "Machine wrist extension, palms down. Steady tension on the extensors." },
  { id: "behind-back-wrist-curl", name: "Behind-the-Back Wrist Curl", category: "Forearms", musclesWorked: ["Forearms"], description: "Barbell held behind the body, curl at the wrists. Deep flexor work." },
  { id: "reverse-barbell-curl", name: "Reverse Barbell Curl", category: "Forearms", musclesWorked: ["Forearms", "Biceps"], description: "Overhand curl targeting the brachioradialis and forearms." },
  { id: "wrist-roller", name: "Wrist Roller", category: "Forearms", musclesWorked: ["Forearms"], description: "Roll a weighted cord up and down. Brutal forearm endurance." },
  { id: "farmers-carry", name: "Farmer's Carry", category: "Forearms", musclesWorked: ["Forearms", "Traps", "Core"], description: "Walk carrying heavy loads. Grip, traps, and core conditioning." },
  { id: "plate-pinch", name: "Plate Pinch", category: "Forearms", musclesWorked: ["Forearms"], description: "Pinch plates together and hold. Direct grip and thumb strength." },
  { id: "dead-hang", name: "Dead Hang", category: "Forearms", musclesWorked: ["Forearms", "Lats"], description: "Hang from a bar for time. Grip endurance and shoulder decompression." },

  // Legs
  { id: "squat", name: "Back Squat", category: "Legs", musclesWorked: ["Quads", "Glutes", "Hamstrings", "Core"], description: "Bar on upper traps. Depth below parallel, knees track toes." },
  { id: "front-squat", name: "Front Squat", category: "Legs", musclesWorked: ["Quads", "Core", "Glutes"], description: "Bar on front delts. More quad emphasis and core demand." },
  { id: "goblet-squat", name: "Goblet Squat", category: "Legs", musclesWorked: ["Quads", "Glutes"], description: "Hold a dumbbell at the chest. Great for depth and beginners." },
  { id: "smith-squat", name: "Smith Machine Squat", category: "Legs", musclesWorked: ["Quads", "Glutes"], description: "Fixed bar path lets you push quads hard with less balance demand." },
  { id: "box-squat", name: "Box Squat", category: "Legs", musclesWorked: ["Quads", "Glutes", "Hamstrings"], description: "Squat to a box for consistent depth and explosive drive off it." },
  { id: "safety-bar-squat", name: "Safety Bar Squat", category: "Legs", musclesWorked: ["Quads", "Glutes", "Core"], description: "Padded yoke bar. Upright torso, shoulder-friendly squatting." },
  { id: "hack-squat", name: "Hack Squat", category: "Legs", musclesWorked: ["Quads", "Glutes"], description: "Machine squat variation. Upright torso, quad dominant." },
  { id: "pendulum-squat", name: "Pendulum Squat", category: "Legs", musclesWorked: ["Quads", "Glutes"], description: "Arced machine path with a deep stretch. Heavy quad emphasis." },
  { id: "belt-squat", name: "Belt Squat", category: "Legs", musclesWorked: ["Quads", "Glutes"], description: "Load hangs from the hips. Trains legs with zero spinal load." },
  { id: "leg-press", name: "Leg Press", category: "Legs", musclesWorked: ["Quads", "Glutes", "Hamstrings"], description: "Machine-based pressing. Foot placement alters emphasis." },
  { id: "single-leg-press", name: "Single-Leg Press", category: "Legs", musclesWorked: ["Quads", "Glutes"], description: "One leg at a time on the leg press. Fixes side-to-side imbalances." },
  { id: "lunges", name: "Lunges", category: "Legs", musclesWorked: ["Quads", "Glutes", "Hamstrings"], description: "Walking or stationary. Unilateral movement for balance." },
  { id: "walking-lunge", name: "Walking Lunge", category: "Legs", musclesWorked: ["Quads", "Glutes", "Hamstrings"], description: "Step forward continuously. Loaded unilateral leg and glute work." },
  { id: "reverse-lunge", name: "Reverse Lunge", category: "Legs", musclesWorked: ["Quads", "Glutes"], description: "Step back into the lunge. Easier on the knees than forward lunges." },
  { id: "bulgarian-squat", name: "Bulgarian Split Squat", category: "Legs", musclesWorked: ["Quads", "Glutes"], description: "Rear foot elevated. Demanding unilateral leg exercise." },
  { id: "step-up", name: "Step-Up", category: "Legs", musclesWorked: ["Quads", "Glutes"], description: "Drive up onto a box. Unilateral quad and glute strength." },
  { id: "sissy-squat", name: "Sissy Squat", category: "Legs", musclesWorked: ["Quads"], description: "Lean back on the toes for an intense quad stretch and contraction." },
  { id: "leg-extension", name: "Leg Extension", category: "Legs", musclesWorked: ["Quads"], description: "Direct quad isolation. Control the eccentric." },
  { id: "romanian-dl", name: "Romanian Deadlift", category: "Legs", musclesWorked: ["Hamstrings", "Glutes", "Back"], description: "Hip hinge with minimal knee bend. Maximum hamstring stretch." },
  { id: "good-morning", name: "Good Morning", category: "Legs", musclesWorked: ["Hamstrings", "Glutes", "Lower Back"], description: "Barbell on the back, hinge forward. Hamstring and posterior-chain builder." },
  { id: "leg-curl", name: "Lying Leg Curl", category: "Legs", musclesWorked: ["Hamstrings"], description: "Face-down machine curl. Direct hamstring isolation." },
  { id: "seated-leg-curl", name: "Seated Leg Curl", category: "Legs", musclesWorked: ["Hamstrings"], description: "Upright machine curl with the hips flexed. Strong hamstring stretch." },
  { id: "nordic-curl", name: "Nordic Hamstring Curl", category: "Legs", musclesWorked: ["Hamstrings"], description: "Lower the body under control with anchored ankles. Elite eccentric strength." },
  { id: "glute-ham-raise", name: "Glute-Ham Raise", category: "Legs", musclesWorked: ["Hamstrings", "Glutes"], description: "GHD bench raise. Powerful hamstring and glute contraction." },
  { id: "adductor-machine", name: "Adductor Machine", category: "Legs", musclesWorked: ["Hip Flexors"], description: "Squeeze the pads together. Isolates the inner-thigh adductors." },
  { id: "calf-raise", name: "Calf Raise", category: "Legs", musclesWorked: ["Calves"], description: "Standing or seated. Full range, pause at bottom." },
  { id: "seated-calf-raise", name: "Seated Calf Raise", category: "Legs", musclesWorked: ["Calves"], description: "Knees bent to bias the soleus. Slow, full-range reps." },
  { id: "leg-press-calf-raise", name: "Leg Press Calf Raise", category: "Legs", musclesWorked: ["Calves"], description: "Push through the balls of the feet on the leg press. Heavy calf loading." },
  { id: "donkey-calf-raise", name: "Donkey Calf Raise", category: "Legs", musclesWorked: ["Calves"], description: "Hip-hinged calf raise for a huge stretch on the gastrocnemius." },
  { id: "tibialis-raise", name: "Tibialis Raise", category: "Legs", musclesWorked: ["Tibialis"], description: "Heels down, pull the toes up toward the shins against a wall or plate. Builds the tibialis anterior (front of the shin) for knee health." },

  // Glutes
  { id: "hip-thrust", name: "Hip Thrust", category: "Glutes", musclesWorked: ["Glutes", "Hamstrings"], description: "Bar over hips, drive upward. The premier glute exercise." },
  { id: "machine-hip-thrust", name: "Machine Hip Thrust", category: "Glutes", musclesWorked: ["Glutes", "Hamstrings"], description: "Plate-loaded thrust machine. Easy setup and heavy loading." },
  { id: "single-leg-hip-thrust", name: "Single-Leg Hip Thrust", category: "Glutes", musclesWorked: ["Glutes"], description: "One leg at a time for unilateral glute strength and balance." },
  { id: "b-stance-hip-thrust", name: "B-Stance Hip Thrust", category: "Glutes", musclesWorked: ["Glutes"], description: "Staggered stance shifts most load onto the working glute." },
  { id: "glute-bridge", name: "Glute Bridge", category: "Glutes", musclesWorked: ["Glutes", "Hamstrings"], description: "Floor-based hip extension. Controlled squeeze at top." },
  { id: "cable-pull-through", name: "Cable Pull-Through", category: "Glutes", musclesWorked: ["Glutes", "Hamstrings"], description: "Hip hinge against a low cable. Teaches a strong glute lockout." },
  { id: "cable-kickback", name: "Cable Kickback", category: "Glutes", musclesWorked: ["Glutes"], description: "Ankle attachment, extend leg back. Direct glute isolation." },
  { id: "reverse-hyper", name: "Reverse Hyperextension", category: "Glutes", musclesWorked: ["Glutes", "Hamstrings", "Lower Back"], description: "Swing the legs up behind you. Glutes, hams, and low-back health." },
  { id: "sumo-dl", name: "Sumo Deadlift", category: "Glutes", musclesWorked: ["Glutes", "Hamstrings", "Quads"], description: "Wide stance, vertical torso. Greater hip abductor involvement." },
  { id: "curtsy-lunge", name: "Curtsy Lunge", category: "Glutes", musclesWorked: ["Glutes", "Quads"], description: "Step behind and across. Targets the gluteus medius." },
  { id: "abduction-machine", name: "Hip Abduction Machine", category: "Glutes", musclesWorked: ["Glutes"], description: "Seated abduction. Targets gluteus medius and minimus." },
  { id: "banded-lateral-walk", name: "Banded Lateral Walk", category: "Glutes", musclesWorked: ["Glutes"], description: "Band around the knees, step sideways. Glute-medius activation." },
  { id: "frog-pump", name: "Frog Pump", category: "Glutes", musclesWorked: ["Glutes"], description: "Soles together, pump the hips up. High-rep glute burnout." },

  // Core
  { id: "plank", name: "Plank", category: "Core", musclesWorked: ["Core"], description: "Maintain rigid body position. Breathe throughout." },
  { id: "side-plank", name: "Side Plank", category: "Core", musclesWorked: ["Obliques", "Core"], description: "Lateral stability hold. Targets obliques and QL." },
  { id: "hollow-hold", name: "Hollow Body Hold", category: "Core", musclesWorked: ["Abs"], description: "Lower back pressed down, limbs extended. Total anterior-core tension." },
  { id: "crunch", name: "Crunch", category: "Core", musclesWorked: ["Abs"], description: "Curl the shoulders off the floor. Classic upper-ab movement." },
  { id: "sit-up", name: "Sit-Up", category: "Core", musclesWorked: ["Abs", "Hip Flexors"], description: "Full flexion from lying to seated. Trains the abs and hip flexors." },
  { id: "decline-sit-up", name: "Decline Sit-Up", category: "Core", musclesWorked: ["Abs", "Hip Flexors"], description: "Sit-up on a decline bench for added resistance." },
  { id: "bicycle-crunch", name: "Bicycle Crunch", category: "Core", musclesWorked: ["Abs", "Obliques"], description: "Alternate elbow to opposite knee. Hits abs and obliques." },
  { id: "reverse-crunch", name: "Reverse Crunch", category: "Core", musclesWorked: ["Abs"], description: "Curl the hips toward the ribs. Lower-ab emphasis." },
  { id: "cable-crunch", name: "Cable Crunch", category: "Core", musclesWorked: ["Abs"], description: "Loaded flexion. Curl elbows toward knees." },
  { id: "ab-crunch-machine", name: "Ab Crunch Machine", category: "Core", musclesWorked: ["Abs"], description: "Seated machine crunch. Easy to load progressively." },
  { id: "hanging-leg-raise", name: "Hanging Leg Raise", category: "Core", musclesWorked: ["Abs", "Hip Flexors"], description: "Dead hang, raise legs to 90° or higher." },
  { id: "leg-raise", name: "Lying Leg Raise", category: "Core", musclesWorked: ["Abs", "Hip Flexors"], description: "Raise straight legs from the floor. Lower-ab focus." },
  { id: "toes-to-bar", name: "Toes-to-Bar", category: "Core", musclesWorked: ["Abs", "Hip Flexors"], description: "Hang and bring the toes to the bar. Advanced ab and grip control." },
  { id: "flutter-kick", name: "Flutter Kicks", category: "Core", musclesWorked: ["Abs", "Hip Flexors"], description: "Small alternating leg kicks. Lower-ab endurance." },
  { id: "v-up", name: "V-Up", category: "Core", musclesWorked: ["Abs"], description: "Simultaneously raise the torso and legs to meet. Full-ab contraction." },
  { id: "ab-rollout", name: "Ab Wheel Rollout", category: "Core", musclesWorked: ["Abs"], description: "Advanced anti-extension. Brutal for core strength." },
  { id: "dead-bug", name: "Dead Bug", category: "Core", musclesWorked: ["Abs"], description: "Extend opposite arm and leg while bracing. Anti-extension control." },
  { id: "russian-twist", name: "Russian Twist", category: "Core", musclesWorked: ["Obliques", "Core"], description: "Seated rotation with weight. Oblique focus." },
  { id: "pallof-press", name: "Pallof Press", category: "Core", musclesWorked: ["Obliques", "Abs"], description: "Press a cable straight out and resist rotation. Anti-rotation strength." },
  { id: "woodchopper", name: "Cable Woodchopper", category: "Core", musclesWorked: ["Obliques", "Abs"], description: "Diagonal cable chop across the body. Rotational core power." },

  // Cardio
  { id: "running", name: "Running", category: "Cardio", musclesWorked: ["Legs", "Core", "Cardio"], description: "Steady state or intervals. Track pace and distance." },
  { id: "treadmill", name: "Treadmill", category: "Cardio", musclesWorked: ["Legs", "Cardio"], description: "Indoor running or walking with adjustable speed and incline." },
  { id: "incline-walk", name: "Incline Walk", category: "Cardio", musclesWorked: ["Glutes", "Legs", "Cardio"], description: "Steep treadmill walk. Low-impact cardio with glute emphasis." },
  { id: "walking", name: "Walking", category: "Cardio", musclesWorked: ["Legs", "Cardio"], description: "Easy steady-state cardio and active recovery. Track steps or distance." },
  { id: "cycling", name: "Cycling", category: "Cardio", musclesWorked: ["Legs", "Cardio"], description: "Low impact cardio. Stationary or outdoor." },
  { id: "assault-bike", name: "Assault Bike", category: "Cardio", musclesWorked: ["Legs", "Core", "Cardio"], description: "Fan bike using arms and legs. Punishing conditioning intervals." },
  { id: "elliptical", name: "Elliptical", category: "Cardio", musclesWorked: ["Legs", "Cardio"], description: "Low-impact full-stride cardio. Easy on the joints." },
  { id: "rowing", name: "Rowing Machine", category: "Cardio", musclesWorked: ["Back", "Legs", "Cardio"], description: "Full body cardio. Drive with legs, pull with back." },
  { id: "ski-erg", name: "Ski Erg", category: "Cardio", musclesWorked: ["Back", "Core", "Cardio"], description: "Double-pole skiing machine. Upper-body and core conditioning." },
  { id: "stairmaster", name: "StairMaster", category: "Cardio", musclesWorked: ["Glutes", "Legs", "Cardio"], description: "Simulated stair climbing. Cardio with glute emphasis." },
  { id: "jump-rope", name: "Jump Rope", category: "Cardio", musclesWorked: ["Calves", "Cardio", "Shoulders"], description: "High intensity. Excellent for conditioning and coordination." },
  { id: "battle-ropes", name: "Battle Ropes", category: "Cardio", musclesWorked: ["Shoulders", "Core", "Cardio"], description: "Wave heavy ropes. Upper-body power endurance." },
  { id: "burpees", name: "Burpees", category: "Cardio", musclesWorked: ["Legs", "Core", "Cardio"], description: "Squat, plank, jump. Full-body conditioning staple." },
  { id: "box-jump", name: "Box Jumps", category: "Cardio", musclesWorked: ["Quads", "Glutes", "Cardio"], description: "Explosive jump onto a box. Power and conditioning." },
  { id: "sled-push", name: "Sled Push", category: "Cardio", musclesWorked: ["Quads", "Glutes", "Cardio"], description: "Drive a loaded sled. Brutal legs and conditioning with no eccentric." },
];

export const MUSCLE_GROUPS = [
  "All", "Chest", "Back", "Shoulders", "Biceps", "Triceps", "Forearms", "Legs", "Glutes", "Core", "Cardio"
] as const;

export const WORKOUT_TEMPLATES = [
  {
    name: "Push Day",
    description: "Chest, shoulders, triceps",
    exercises: ["bench-press", "ohp", "incline-bench", "lateral-raise", "tricep-pushdown", "skull-crusher"],
    icon: "💪",
  },
  {
    name: "Pull Day",
    description: "Back, biceps, rear delts",
    exercises: ["deadlift", "pull-up", "barbell-row", "lat-pulldown", "barbell-curl", "face-pull"],
    icon: "🏋️",
  },
  {
    name: "Leg Day",
    description: "Quads, hamstrings, glutes, calves",
    exercises: ["squat", "romanian-dl", "leg-press", "lunges", "leg-curl", "calf-raise"],
    icon: "🦵",
  },
  {
    name: "Upper Body",
    description: "Full upper body",
    exercises: ["bench-press", "barbell-row", "ohp", "pull-up", "barbell-curl", "tricep-pushdown"],
    icon: "🔝",
  },
  {
    name: "Full Body",
    description: "Total body compound movements",
    exercises: ["squat", "bench-press", "deadlift", "ohp", "barbell-row", "pull-up"],
    icon: "⚡",
  },
];
